# Platform metadata and configuration
artifakt_version: "0.3"
tag: "0.0.3"
build_engine: terraform
available_regions:
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
  - ca-central-1
  - eu-central-1
  - eu-west-1
  - eu-west-2
  - eu-west-3
  - ap-northeast-1
  - ap-northeast-2
  - ap-northeast-3
  - ap-southeast-1
  - ap-southeast-2
  - ap-south-1
  - sa-east-1
infrastructure:
  build_time: 15 #in seconds 
  cost_estimation:
    monthly_price: 0.04  #in dollars per month 
    details: calculated for 5K Get request per month and used space under 1Go in Ireland 

inputs:
  - 
    code: bucket_name
    name: Bucket name
    description: Choose your bucket name, must be unique and lowercase
    category: data
    type: text 
    default: default
    required: false
      
outputs:
  - 
    code: main_endpoint
    name: Website URL
    description: Fully qualified website URL 
    category: Application
  - 
    code: BUCKET_NAME
    name: Bucket name
    description: Bucket name
    category: Application
  
  
actions:
  -
    code: publish
    name: Publish
    description: Publish new content
    engine: shell
    script: publish.sh
    params:
      - 
        code: content
        name: Content
        type: textarea
        required: true
